# application port number
server:
  port: 8084

spring:

  # setting application name
  application:
      name: orderservice

  # database configs
  datasource:
    url: jdbc:mysql://localhost:3306/ObviousAI
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # To give the table name and column names as variable name by default. It was taking some other defaults
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Config server
  config:
    import: optional:configserver:http://localhost:8091

# Eureka service discovery/registry configs - Now moved to config server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/